// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

import { defineConfig } from '@prisma/config';
import * as dotenv from 'dotenv';

// Força o carregamento do arquivo .env.local do Next.js
dotenv.config({ path: '.env.local' });

export default defineConfig({
  datasource: {
    // Para migrações, usamos SEMPRE a DIRECT_URL (Porta 5432)
    url: process.env.DIRECT_URL,
  },
});